apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    go-web-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
    selector:
      app: go-web-app
    type: ClusterIP